version: '3.8'

services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=postgres --dbname=school_db"
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - node-crud
    ports:
      - 8000:5432
  prismaproject:
    image: edca3899/node-crud-prisma-hapi-pg
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/school_db?schema=public
    command: npm run serve
    ports:
      - 3000:3000
    networks:
      - node-crud
    depends_on:
      db:
        condition: "service_healthy"
networks:
  node-crud:
    name: node-crud
